import Head from 'next/head';
import { MainStyle } from 'styles/PageStyles';
import NavBar from './NavBar';

export default function Layout({ children }: any) {
  return (
    <>
      <Head>
        <title>Two stage Navigation Menu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainStyle id="myId">
        <NavBar />
        {children}
      </MainStyle>
    </>
  );
}
