import GlobalLayout from './layout/GlobalLayout';
import Head from 'next/head';
import styled from 'styled-components';

// Testing if styled components work
const Title = styled.h1`
  color: rgba(220, 36, 31, 1);
`;

export default function Home() {
  return (
    <>
      <GlobalLayout>
        <Head>
          <title>Two stage Navigation Menu</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <Title>Test Styled components</Title>
        </main>
      </GlobalLayout>
    </>
  );
}
