import { GetServerSideProps, GetServerSidePropsContext } from 'next';

import ChangeLanguage from '@/components/ChangeLanguage';
import GlobalLayout from '@/layout/GlobalLayout';
import Head from 'next/head';
import NavBar from '@/components/NavBar';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useTranslation } from 'next-i18next';

export default function Home() {
  const { t } = useTranslation('common');
  return (
    <>
      <GlobalLayout>
        <Head>
          <title>Two stage Navigation Menu</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <NavBar />
        </main>
      </GlobalLayout>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async ({
  locale,
}: GetServerSidePropsContext) => ({
  props: {
    ...(await serverSideTranslations(locale ?? 'de-CH', ['common'])),
  },
});
